version: '3.4'

services:
  nginx:
    image: nginx:1.16.1
    ports:
      - 8001:80
    working_dir: "/var/www"
    volumes:
      - .:/var/www:rw,delegated
      - ./docker/nginx/conf.d/build_up.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./var/docker/logs/nginx/:/var/log/nginx:cached
    links:
      - php
    restart: on-failure

  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    working_dir: "/var/www"
    volumes:
      - .:/var/www:rw,delegated
      - ./var/docker/logs/php/:/var/log/build_up:cached
    links:
      - mysql
      - redis
      - mail
    depends_on:
      - mysql
    restart: on-failure

  mysql:
    image: mysql:5.7
    ports:
      - 8081:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
    restart: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    depends_on:
      - mysql
    restart: on-failure
    ports:
      - 8000:80
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASS}

  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  redis:
    image: redis:5.0.8-alpine


volumes:
  mysql_data:
    driver: local