version: '3.4'

services:
  nginx:
    image: nginx:1.16.1
    ports:
      - 8000:80
    volumes:
      - .:${WORKING_DIRECTORY}
      - ./docker/nginx/conf.d/build_up.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/logs/nginx/:/var/log/nginx:cached
    links:
      - php
    restart: on-failure

  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - .:${WORKING_DIRECTORY}
      - ./docker/logs/php/:/var/log/build_up:cached
    links:
      - mysql
      - redis
      - mail
    depends_on:
      - mysql
    restart: on-failure

  mysql:
    image: mysql:5.7
    ports:
      - 8081:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_NAME}
    restart: on-failure
    networks: 
      - build_up_network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    networks:
      - build_up_network

  mail:
    image: schickling/mailcatcher
    ports:
      - 1080:1080

  redis:
    image: redis:5.0.8-alpine


networks: 
  build_up_network:

volumes:
  mysql_data:
    driver: local